/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ScrapingJob } from "./ScrapingJob";
import { ScrapingJobCountArgs } from "./ScrapingJobCountArgs";
import { ScrapingJobFindManyArgs } from "./ScrapingJobFindManyArgs";
import { ScrapingJobFindUniqueArgs } from "./ScrapingJobFindUniqueArgs";
import { DeleteScrapingJobArgs } from "./DeleteScrapingJobArgs";
import { ScrapingJobService } from "../scrapingJob.service";
@graphql.Resolver(() => ScrapingJob)
export class ScrapingJobResolverBase {
  constructor(protected readonly service: ScrapingJobService) {}

  async _scrapingJobsMeta(
    @graphql.Args() args: ScrapingJobCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ScrapingJob])
  async scrapingJobs(
    @graphql.Args() args: ScrapingJobFindManyArgs
  ): Promise<ScrapingJob[]> {
    return this.service.scrapingJobs(args);
  }

  @graphql.Query(() => ScrapingJob, { nullable: true })
  async scrapingJob(
    @graphql.Args() args: ScrapingJobFindUniqueArgs
  ): Promise<ScrapingJob | null> {
    const result = await this.service.scrapingJob(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ScrapingJob)
  async deleteScrapingJob(
    @graphql.Args() args: DeleteScrapingJobArgs
  ): Promise<ScrapingJob | null> {
    try {
      return await this.service.deleteScrapingJob(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
